# Initial Exploration of Biblical Texts

Name: Isaac Anderson

Date: Sept 3 2025

This problem set must accomplish the following tasks:

**Zipf's law**: in natural language, the frequency of a word is inversely proportion to its rank. e.g. the second more frequent word occurs half as often as the first most frequent word. So the top few words cover a huge fraction of the text.
If you have $n$ total tokens and sorted counts $f_1, f_2, \ldots, f_3$, the coverage of the first k terms is $C_k = \frac{\sum_{i=1}^k f_i}{n}$
The ideal Zipf prediction is $p(k) \propto 1/k$. For a finite vocabulary size of $n$, the ideal Zipf prediction is $p(k) = \frac{1/k}{\sum_{i=1}^n 1/i}$


7. Identify a way to drop out the content-less words and then plot the coverage of these new top 20 lemmas and list them in a table along with their Strong's definitions. On this same plot, plot the ideal Zipf prediction for a finite vocabulary size.

8. Pickle your dataframes.

My WORKINGS.

In [1]:
# Dependancies
import pandas as pd
from bs4 import BeautifulSoup # requires lxml

1. Read in 'SF_2009-01-20_GRC_TISCHENDORF_(TISCHENDORF GREEK NT(STRONGS)).xml' and save data to a dataframe (one word per row).

In [2]:
tisch_greek = pd.read_xml(
                        "../Data/SF_2009-01-20_GRC_TISCHENDORF_(TISCHENDORF GREEK NT(STRONGS)).xml",
                        parser = "lxml",
                        xpath = "/XMLBIBLE//BIBLEBOOK//CHAPTER//VERS/gr")
tisch_greek.head()

      str   rmac         gr STYLE
0   976.0  n-nsf    Βίβλος   None
1  1078.0  n-gsf  γενέσεως   None
2  2424.0  n-gsm     Ἰησοῦ   None
3  5547.0  n-gsm   Χριστοῦ   None
4  5207.0  n-gsm      υἱοῦ   None

2. Parse the rmac codes.

In [3]:
# filtering rmacs
tisch_greek['rmac'] = tisch_greek['rmac'].str.lower()
tisch_greek = tisch_greek[~tisch_greek['rmac'].str.endswith('-')]

In [4]:
from bs4 import BeautifulSoup
import requests
import pandas as pd
import re

In [5]:
# Getting a list of all RMACS
index_url = "https://www.modernliteralversion.org/bibles/bs2/RMAC/RMACindex.html"
rmac_url = "https://www.modernliteralversion.org/bibles/bs2/RMAC/"

# Get the metadata for all possible rmacs.
response = requests.get(index_url)
soup = BeautifulSoup(response.text, 'html5lib')

all_links = soup.find('blockquote').find_all('a')

all_rmacs = []
hrefs = []
for link in all_links:
    hrefs.append(link.get('href'))
    all_rmacs.append(link.text.strip())

In [6]:
## RMAC SCRAPPER
all_labels = [] # used for making rmac database columns.
def decode_rmac(rmac_link: str) -> list:
    print(rmac_url+rmac_link)
    response = requests.get(rmac_url+rmac_link)
    rmac_soup = BeautifulSoup(response.text, 'html5lib')
    rows  = rmac_soup.find_all('tr')
    first_entry = rows[2]

    lines = first_entry.text.split("\n")
    meaningful_lines = []
    for line in lines:
        cleaned_item = line.strip()
        if re.search(r"\w+\: ",cleaned_item):
            cleaned_item = cleaned_item.strip()
            meaningful_lines.append(cleaned_item)
            

    rmac_decoded = []
    for line in meaningful_lines:
        label = re.search(r"(\w+)\:", line).group()
        meaning = re.search(r"(?<=: )\w+", line).group()
        rmac_decoded.append({label: meaning})

        all_labels.append(label) # This is for creating columns down the line. 
    return rmac_decoded

In [7]:
# only scraping the website when absolutely necessary.
import os

if os.path.exists("./all_rmacs_decoded"):
    rmacs_df = pd.read_csv("./all_rmacs_decoded")
else:
    rmacs_df = pd.DataFrame()
    rmacs_df['rmac'] = all_rmacs
    rmacs_df.head()
    rmac_url = "https://www.modernliteralversion.org/bibles/bs2/RMAC/"

    for index, row in rmacs_df.iterrows():
        decoded_rmac_parts = decode_rmac(row['rmac']+".htm")

        for dict_segment in decoded_rmac_parts:
            rmacs_df.at[index, list(dict_segment.keys())[0]] = list(dict_segment.values())[0]

    rmacs_df.to_csv("./all_rmacs_decoded")

In [8]:
rmacs_df['rmac'] = rmacs_df['rmac'].str.lower()
tisch_rmac_df = pd.merge(
    rmacs_df,
    tisch_greek,
    left_on="rmac",
    right_on="rmac"
)
tisch_rmac_df = tisch_rmac_df[
    ["rmac","str","gr","STYLE", "Speech:", "Case:", 
     "Number:","Gender:", "Degree:", "Form:","Tense:",
     "Voice:", "Mood:", "Person:"]
]

3. Read in 'strongs-dictionary.xhtml' and save data to a dataframe (one term per row).

In [9]:
with open("../Data/strongs-dictionary.xhtml", "r", encoding="utf-8") as file:
    raw_text = file.read()

strongs_soup = BeautifulSoup(raw_text, 'xml')

strongs_columns = strongs_soup.find('section', id="nt").find("ol").find_all("li")

In [10]:
rows = []
for entry in strongs_columns:
    row = {}
    rows.append({
        "strongs_number": entry.get("value"),
        "lemma": entry.find("i").text,
        "kjv-def": entry.find("span", class_="kjv_def").text if entry.find("span", class_="kjv_def") else None
    })

In [11]:
strongs_df = pd.DataFrame(data=rows)
strongs_df.set_index("strongs_number", inplace=True)
strongs_df['easy-def'] = strongs_df['kjv-def'].str.split().str[0]
strongs_df

# pickles
strongs_df.to_pickle("./pickles/ps1/strongs_dictionary")

4. Compute top 50 lemmas by frequency

In [12]:
top50_lemmas = pd.DataFrame(tisch_rmac_df['str'].value_counts().nlargest(50))
top50_lemmas.index = top50_lemmas.index.astype(int)
display(top50_lemmas.index)

Index([3588, 2532,  846, 1161, 1722, 1510, 3004, 5210, 1519, 1473, 3756, 3739,
       3778, 2316, 3754, 3956, 4771, 1063, 3361, 1537, 2424, 1909, 2248, 2962,
       2192, 4314, 3708, 1096, 2443,  575,  235, 1223, 2064, 4160,  444, 5101,
       5547, 5100, 5613, 1487, 3767, 2596, 3326,  191, 1325, 3962, 2250, 4151,
       5207, 4183],
      dtype='int64', name='str')

## Question 5: Coverage of top 20 lemmas.

In [13]:
import plotly.express as px

In [14]:
strongs_df.index = strongs_df.index.astype(int)

In [15]:
top20_lemmas = pd.DataFrame(tisch_rmac_df['str'].value_counts().nlargest(20))
top20_lemmas.index = top20_lemmas.index.astype(int)
top20_lemmas.head()

      count
str
3588  19756
2532   8967
846    5555
1161   2770
1722   2739

In [16]:
top20_df = pd.merge(
    strongs_df,
    top20_lemmas, 
    right_index=True, 
    left_index=True
)
top20_df.index.name = "strongs-number"
display(top20_df.head(5))

,lemma,kjv-def,easy-def,count
strongs-number,,,,
846,αὐτός,"her, it(-self), one, the other, (mine) own, sa...","her,",5555
1063,γάρ,"and, as, because (that), but, even, for, indee...","and,",1036
1161,δέ,"also, and, but, moreover, now (often unexpress...","also,",2770
1473,ἐγώ,"I, me","I,",1718
1510,εἰμί,"am, have been, X it is I, was","am,",2459

6. Plot the coverage of the top 20 lemmas and list them in a table along with their Strong's definitions. On this same plot, plot the ideal Zipf prediction for a finite vocabulary size.

In [21]:
sorted = top20_df.sort_values(
    by='count',
    ascending=False,
)
sorted

,lemma,kjv-def,easy-def,count
strongs-number,,,,
3588,ὁ,"the, this, that, one, he, she, it, etc","the,",19756
2532,καί,"and, also, both, but, even, for, if, or, so, t...","and,",8967
846,αὐτός,"her, it(-self), one, the other, (mine) own, sa...","her,",5555
1161,δέ,"also, and, but, moreover, now (often unexpress...","also,",2770
1722,ἐν,"about, after, against, + almost, X altogether,...","about,",2739
1510,εἰμί,"am, have been, X it is I, was","am,",2459
3004,λέγω,"ask, bid, boast, call, describe, give out, nam...","ask,",2250
5210,ὑμεῖς,"ye (yourselves), you",ye,1828
1519,εἰς,"(abundant-)ly, against, among, as, at, (back-)...","(abundant-)ly,",1764
1473,ἐγώ,"I, me","I,",1718
3756,οὐ,"+ long, nay, neither, never, no (X man), none,...",+,1626
3739,ὅς,"one, (an-, the) other, some, that, what, which...","one,",1404
3778,οὗτος,"he (it was that), hereof, it, she, such as, th...",he,1378
2316,θεός,"X exceeding, God, god(-ly, -ward)",X,1312
3754,ὅτι,"as concerning that, as though, because (that),...",as,1299
3956,πᾶς,"all (manner of, means), alway(-s), any (one), ...",all,1225
4771,σύ,thou,thou,1068
1063,γάρ,"and, as, because (that), but, even, for, indee...","and,",1036
3361,μή,"any but (that), X forbear, + God forbid, + lac...",any,1033
1537,ἐκ,"after, among, X are, at, betwixt(-yond), by (t...","after,",915

In [22]:
top20_df
fig = px.bar(sorted, x='lemma', y='count')
fig.show()

## Question 7