# Initial Exploration of Biblical Texts

Name: Isaac Anderson

Date: Sept 3 2025

This problem set must accomplish the following tasks:

**Zipf's law**: in natural language, the frequency of a word is inversely proportion to its rank. e.g. the second more frequent word occurs half as often as the first most frequent word. So the top few words cover a huge fraction of the text.
If you have $n$ total tokens and sorted counts $f_1, f_2, \ldots, f_3$, the coverage of the first k terms is $C_k = \frac{\sum_{i=1}^k f_i}{n}$
The ideal Zipf prediction is $p(k) \propto 1/k$. For a finite vocabulary size of $n$, the ideal Zipf prediction is $p(k) = \frac{1/k}{\sum_{i=1}^n 1/i}$

6. Plot the coverage of the top 20 lemmas and list them in a table along with their Strong's definitions. On this same plot, plot the ideal Zipf prediction for a finite vocabulary size.
7. Identify a way to drop out the content-less words and then plot the coverage of these new top 20 lemmas and list them in a table along with their Strong's definitions. On this same plot, plot the ideal Zipf prediction for a finite vocabulary size.

8. Pickle your dataframes.

My WORKINGS.

In [5]:
# Dependancies
import pandas as pd
from bs4 import BeautifulSoup # requires lxml

1. Read in 'SF_2009-01-20_GRC_TISCHENDORF_(TISCHENDORF GREEK NT(STRONGS)).xml' and save data to a dataframe (one word per row).

In [6]:
tisch_greek = pd.read_xml(
                        "../Data/SF_2009-01-20_GRC_TISCHENDORF_(TISCHENDORF GREEK NT(STRONGS)).xml",
                        parser = "lxml",
                        xpath = "/XMLBIBLE//BIBLEBOOK//CHAPTER//VERS/gr")
tisch_greek.head()

      str   rmac         gr STYLE
0   976.0  n-nsf    Βίβλος   None
1  1078.0  n-gsf  γενέσεως   None
2  2424.0  n-gsm     Ἰησοῦ   None
3  5547.0  n-gsm   Χριστοῦ   None
4  5207.0  n-gsm      υἱοῦ   None

2. Parse the rmac codes.

In [7]:
# filtering rmacs
tisch_greek['rmac'] = tisch_greek['rmac'].str.lower()
tisch_greek = tisch_greek[~tisch_greek['rmac'].str.endswith('-')]

In [ ]:
from bs4 import BeautifulSoup
import requests
import pandas as pd
import re

In [19]:
# Getting a list of all RMACS
index_url = "https://www.modernliteralversion.org/bibles/bs2/RMAC/RMACindex.html"
rmac_url = "https://www.modernliteralversion.org/bibles/bs2/RMAC/"

# Get the metadata for all possible rmacs.
response = requests.get(index_url)
soup = BeautifulSoup(response.text, 'html5lib')

all_links = soup.find('blockquote').find_all('a')

all_rmacs = []
hrefs = []
for link in all_links:
    hrefs.append(link.get('href'))
    all_rmacs.append(link.text.strip())

In [ ]:
## RMAC SCRAPPER
all_labels = [] # used for making rmac database columns.
def decode_rmac(rmac_link: str) -> list:
    print(rmac_url+rmac_link)
    response = requests.get(rmac_url+rmac_link)
    rmac_soup = BeautifulSoup(response.text, 'html5lib')
    rows  = rmac_soup.find_all('tr')
    first_entry = rows[2]

    lines = first_entry.text.split("\n")
    meaningful_lines = []
    for line in lines:
        cleaned_item = line.strip()
        if re.search(r"\w+\: ",cleaned_item):
            cleaned_item = cleaned_item.strip()
            meaningful_lines.append(cleaned_item)
            

    rmac_decoded = []
    for line in meaningful_lines:
        label = re.search(r"(\w+)\:", line).group()
        meaning = re.search(r"(?<=: )\w+", line).group()
        rmac_decoded.append({label: meaning})

        all_labels.append(label) # This is for creating columns down the line. 
    return rmac_decoded

In [10]:
# only scraping the website when absolutely necessary.
import os

if os.path.exists("./all_rmacs_decoded"):
    rmacs_df = pd.read_csv("./all_rmacs_decoded")
else:
    rmacs_df = pd.DataFrame()
    rmacs_df['rmac'] = all_rmacs
    rmacs_df.head()
    rmac_url = "https://www.modernliteralversion.org/bibles/bs2/RMAC/"

    for index, row in rmacs_df.iterrows():
        decoded_rmac_parts = decode_rmac(row['rmac']+".htm")

        for dict_segment in decoded_rmac_parts:
            rmacs_df.at[index, list(dict_segment.keys())[0]] = list(dict_segment.values())[0]

    rmacs_df.to_csv("./all_rmacs_decoded")

In [11]:
rmacs_df['rmac'] = rmacs_df['rmac'].str.lower()
tisch_rmac_df = pd.merge(
    rmacs_df,
    tisch_greek,
    left_on="rmac",
    right_on="rmac"
)
tisch_rmac_df = tisch_rmac_df[
    ["rmac","str","gr","STYLE", "Speech:", "Case:", 
     "Number:","Gender:", "Degree:", "Form:","Tense:",
     "Voice:", "Mood:", "Person:"]
]

3. Read in 'strongs-dictionary.xhtml' and save data to a dataframe (one term per row).

In [12]:
with open("../Data/strongs-dictionary.xhtml", "r", encoding="utf-8") as file:
    raw_text = file.read()

strongs_soup = BeautifulSoup(raw_text, 'xml')

strongs_columns = strongs_soup.find('section', id="nt").find("ol").find_all("li")

In [13]:
rows = []
for entry in strongs_columns:
    row = {}
    rows.append({
        "strongs_number": entry.get("value"),
        "lemma": entry.find("i").text,
        "kjv-def": entry.find("span", class_="kjv_def").text if entry.find("span", class_="kjv_def") else None
    })

In [14]:
strongs_df = pd.DataFrame(data=rows)
strongs_df.set_index("strongs_number", inplace=True)
strongs_df

# pickles
strongs_df.to_pickle("./pickles/ps1/strongs_dictionary")

4. Compute top 50 lemmas by frequency

In [18]:
top50_lemmas = tisch_greek['str'].value_counts().nlargest(50)
top50_lemmas = pd.merge(
    left = top50_lemmas,
    right = tisch_greek,
    left_index=True,
    right_on="str"
)
top50_lemmas.head()

    count     str   rmac     gr STYLE
10  19756  3588.0  t-asm   τὸν   None
15  19756  3588.0  t-asm   τὸν   None
20  19756  3588.0  t-asm   τὸν   None
23  19756  3588.0  t-apm  τοὺς   None
29  19756  3588.0  t-asm   τὸν   None

## Question 5: Coverage of top 20 lemmas.

## Question 7