# Statistical Tests

Name: **Isaac Anderson**

Date: **16 Sept 2025**

## Hypothesis Tests

### Means
1. Identify 5 theologically salient lemmas from the top 20 lemmas (end of PS1) and compute per verse rates by book.
2. Are the per-verse rates between Synoptic Gospels and John the same for all 5 lemmas.
3. Report effect sizes using Cohen's d along with confidence intervals.
4. Correct these results for multiple tests using the Bonferroni correction.
5. Correct these results for multiple tests using the Benjamini-Hochberg correction.
6. Why are the numbers from the Bonferroni correction different from the Benjamini-Hochberg correction? Which results should you use and why?

### Proportion
7. Are the proportion of term presence vs term absence in verse the same between Synoptic Gospels and John for all 5 lemmas?
8. Report effect sizes using Cohen's d along with confidence intervals.
9. Correct these results for multiple tests using the Bonferroni correction.
10. Correct these results for multiple tests using the Benjamini-Hochberg correction.
6. Why are the numbers from the Bonferroni correction different from the Benjamini-Hochberg correction? Which results should you use and why?

### ANOVA
12. Do a term rate ANOVA comparison on a theologically salient lemma from the top 20 lemmas across the following groups: {Matthew and Mark, Luke and Acts, Johannine books, Pauline books, all other books}
13. Perform a Post-hoc Tukey HSD to see which pairs differ

### Chi-square Test
14. Build a 2xk contingency table for collocation: presence of target term vs top-k companion terms within verse.
15. Run Chi-square tests of independence; compute standardized residuals to find surprising co-occurrences
16. Visualize a heatmap of residuals
17. Explain results

18. Repeat the ANOVA and Chi-square test sections for 2 other terms.

## Power Analysis Extension

18. Conduct a power analysis for the question in #7 to determine how many verses are needed to detect the specified effect.
13. Simulate the answer.
    <ol type="a">
    <li>Simulate n verses with the proportions found in #8 for Synoptic Gospels and John. Do a test to see if significantly different and save this result.</li>
    <li>Repeat step a many times.</li>
    <li>Calculate power: power = (number of significant findings) / (total simulations)</li>
    <li>Repeat steps a-c for a different n.</li>
    <li>Plot power as a function of number of verses.</li>
    <li>At what number of verses is the power at least 80%? i.e. This is the number of verses you need per text to have an 80% chance of detecting the effect if it's really there.</li>
    </ol>

## Sliding Windows Stretch
21. Repeat ANOVA and Chi-square sections on the same three theological terms, but instead of using verse boundaries, use sliding windows (+/- n tokens)
22. How do results of verse boundaries compare to using sliding windows?

## **Problem 1**: Identify 5 theologically salient lemmas from the top 20 lemmas (end of PS1) and compute per verse rates by book.

In [162]:
import pandas as pd

new_testament = pd.read_pickle('../Data/nt.pickle')
top20 = pd.read_pickle("../Data/zipf-top20.pickle")
strongs_dictionary = pd.read_pickle("./pickles/ps1/strongs_dictionary")

##### Finding "Salient" top 20 words (I.E Verbs/Nouns/Adjectives/Adverbs)

In [163]:
new_testament = pd.merge(
    strongs_dictionary,
    new_testament, 
    left_index=True, 
    right_on="strong"
).drop("greek-word", axis=1)
new_testament

,kjv-def,word,rmac,strong,book,chapter,verse,parsed_rmac,strong_definition
127868,Alpha,ἄλφα,N-LI,1,66,1,8,Indeclinable letter (noun),Α of Hebrew origin; the first letter of the al...
136598,Alpha,ἄλφα,N-LI,1,66,21,6,Indeclinable letter (noun),Α of Hebrew origin; the first letter of the al...
137335,Alpha,ἄλφα,N-LI,1,66,22,13,Indeclinable letter (noun),Α of Hebrew origin; the first letter of the al...
29557,Aaron,"Ἀαρών,",N-PRI,2,42,1,5,Indeclinable proper noun,"Ἀαρών of Hebrew origin (אַהֲרוֹן); Aaron, the br..."
68755,Aaron,Ἀαρών·,N-PRI,2,44,7,40,Indeclinable proper noun,"Ἀαρών of Hebrew origin (אַהֲרוֹן); Aaron, the br..."
...,...,...,...,...,...,...,...,...,...
119860,"advantage, better, prevail, profit",ὠφελήθησαν,V-API-3P,5623,58,13,9,Verb - Aorist - Passive - Indicative - 3rd - P...,"ὠφελέω from the same as ὠφέλεια; to be useful,..."
112147,profit(-able),"ὠφέλιμος,",A-NSM,5624,54,4,8,Adjective - Nominative - Singular - Masculine,ὠφέλιμος from a form of ὄφελος; helpful or ser...
112153,profit(-able),ὠφέλιμός,A-NSM,5624,54,4,8,Adjective - Nominative - Singular - Masculine,ὠφέλιμος from a form of ὄφελος; helpful or ser...
113822,profit(-able),ὠφέλιμος,A-NSM,5624,55,3,16,Adjective - Nominative - Singular - Masculine,ὠφέλιμος from a form of ὄφελος; helpful or ser...
114734,profit(-able),ὠφέλιμα,A-NPN,5624,56,3,8,Adjective - Nominative - Plural - Neuter,ὠφέλιμος from a form of ὄφελος; helpful or ser...

In [164]:
# Forming Part of Speech
new_testament["part_speech"] = new_testament["parsed_rmac"].apply(lambda x: x.split()[0])
wanted_part_speech = ["Adjective", "Adverb","Noun","Verb"]
salient_nt = new_testament[new_testament['part_speech'].isin(wanted_part_speech)]

In [165]:
salient_nt['strong'].value_counts()

strong
1510    27049
3004    24761
2316    14432
3956    13475
2424     9944
        ...
3707       11
3703       11
3702       11
3700       11
3698       11
Name: count, Length: 5030, dtype: int64

In [166]:
top20_strongs_num = salient_nt['strong'].value_counts()[:20].to_frame()
top20_strongs_num.columns = ["count"]
top20_df = pd.merge(
    left = top20_strongs_num,
    right = new_testament,
    left_index = True,
    right_on= "strong"
)
top20_df = top20_df.drop_duplicates(subset=['strong'], inplace=False)
top20_df.head()

,count,kjv-def,word,rmac,strong,book,chapter,verse,parsed_rmac,strong_definition,part_speech
282,27049,"am, have been, X it is I, was",ἦν.,V-IAI-3S,1510,40,1,18,Verb - Imperfect - Active - Indicative - 3rd -...,εἰμί the first person singular present indicat...,Verb
244,24761,"ask, bid, boast, call, describe, give out, nam...",λεγόμενος,V-PPP-NSM,3004,40,1,16,Verb - Present - Passive - Participle - Nomina...,"λέγω a primary verb; properly, to ""lay"" forth,...",Verb
402,14432,"X exceeding, God, god(-ly, -ward)",θεός.,N-NSM,2316,40,1,23,Noun - Nominative - Singular - Masculine,"θεός of uncertain affinity; a deity, especiall...",Noun
246,13475,"all (manner of, means), alway(-s), any (one), ...",Πᾶσαι,A-NPF,3956,40,1,17,Adjective - Nominative - Plural - Feminine,πᾶς including all the forms of declension; app...,Adjective
2,9944,Jesus,Ἰησοῦ,N-GSM,2424,40,1,1,Noun - Genitive - Singular - Masculine,Ἰησοῦς of Hebrew origin (יְהוֹשׁ֫וּעַ); Jesus (i....,Noun

#### Picking 5 Theologically Salient Lemmas

In [167]:
salient_lemmas_id = ['1510', '5547', '3962', '4160', '5207']
salient_df = top20_df.loc[top20_df['strong'].astype(str).isin(salient_lemmas_id)]

##### Finding the "per verse" rates by book.

In [168]:
salient_nt = new_testament.loc[new_testament['strong'].astype(str).isin(salient_lemmas_id)]

In [169]:
salient_nt['kjv-def'].value_counts()

kjv-def
am, have been, X it is I, was                                                                                                                                                                                                                                                                                                                                                                                                                                                                              27049
abide, + agree, appoint, X avenge, + band together, be, bear, + bewray, bring (forth), cast out, cause, commit, + content, continue, deal, + without any delay, (would) do(-ing), execute, exercise, fulfil, gain, give, have, hold, X journeying, keep, + lay wait, + lighten the ship, make, X mean, + none of these things move me, observe, ordain, perform, provide, + have purged, purpose, put, + raising up, X secure, shew, X shoot out, spend, take, tarry, + transgress the law, work, yield     6259
Christ                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      5830
father, parent                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              4532
child, foal, son                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            4136
Name: count, dtype: int64

In [170]:
salient_nt.groupby(["strong","book"])['word'].count()[5547]

book
40    176
41     77
42    132
43    209
44    286
45    715
46    693
47    517
48    418
49    506
50    407
51    286
52    110
53    110
54    165
55    143
56     44
57     88
58    132
59     22
60    242
61     88
62     88
63     33
65     66
66     77
Name: word, dtype: int64

In [171]:
bob = (salient_df.query(f"strong == {1510}")['word'].iloc[0])
print(bob)

ἦν.

In [ ]:
per_verse_df = pd.DataFrame(
    {
        "Book":salient_nt['book'].unique(),
        "Total_verses":new_testament.groupby(['book','chapter'])['verse'].agg("max").groupby("book").sum(),
    }
)

greek_lemmas = []
for strong_id in map(int, salient_lemmas_id):
    greek_word = salient_df.query(f"strong == {strong_id}")['word'].iloc[0]
    greek_lemmas.append(greek_word)
    per_verse_df[greek_word] = salient_nt.groupby(["strong","book"])['word'].count()[strong_id]


mentioned_per_verse =  per_verse_df[greek_lemmas].div(per_verse_df['Total_verses'], axis=0)

            ἦν.   Χριστοῦ    πατρὸς  ἐποίησεν      υἱοῦ
book
40     2.968254  0.164332  0.647059  0.883287  0.914099
41     3.098820  0.113569  0.292035  0.778761  0.551622
42     3.450043  0.114683  0.535187  0.850565  0.735882
43     5.568828  0.237770  1.676906  1.364050  0.700796
44     3.047666  0.284012  0.382324  0.742800  0.229394
45     2.870670  1.651270  0.381062  0.584296  0.304850
46     4.052632  1.585812  0.151030  0.352403  0.050343
47     2.653696  2.011673  0.214008  0.385214  0.171206
48     3.912752  2.805369  0.369128  0.442953  0.959732
49     3.406452  3.264516  0.780645  0.709677  0.283871
50     1.798077  3.913462  0.423077  0.317308       NaN
51     3.010526  3.010526  0.578947  0.347368  0.115789
52     1.483146  1.235955  0.617978  0.494382  0.370787
53     1.638298  2.340426  0.702128  0.468085  0.234043
54     2.823009  1.460177  0.194690  0.389381       NaN
55     2.120482  1.722892  0.132530  0.132530       NaN
56     3.826087  0.956522  0.239130  0.239130       NaN
57     1.320000  3.520000  0.440000  1.320000       NaN
58     1.996700  0.435644  0.326733  0.689769  0.871287
59     3.259259  0.203704  0.407407  1.222222  0.101852
60     1.152381  2.304762  0.314286  0.314286  0.104762
61     2.344262  1.442623  0.360656  0.721311  0.180328
62    10.371429  0.838095  1.466667  1.361905  2.304762
63     5.076923  2.538462  3.384615       NaN  1.692308
64     1.466667       NaN       NaN  2.200000       NaN
65     1.760000  2.640000  0.440000  0.880000       NaN
66     2.960494  0.190123  0.135802  0.814815  0.217284

## Problem 2

In [185]:
synoptics_count = mentioned_per_verse.query("book in [40,41,42]")
john_count = mentioned_per_verse.query("book == 43")

print("john counts:")
display(john_count)
print("synoptic counts:")
display(synoptics_count)

john counts:

           ἦν.  Χριστοῦ    πατρὸς  ἐποίησεν      υἱοῦ
book
43    5.568828  0.23777  1.676906   1.36405  0.700796

synoptic counts:

           ἦν.   Χριστοῦ    πατρὸς  ἐποίησεν      υἱοῦ
book
40    2.968254  0.164332  0.647059  0.883287  0.914099
41    3.098820  0.113569  0.292035  0.778761  0.551622
42    3.450043  0.114683  0.535187  0.850565  0.735882

No they are not the same.