# Statistical Tests

Name: **Isaac Anderson**

Date: **16 Sept 2025**

## Hypothesis Tests

### Means
1. Identify 5 theologically salient lemmas from the top 20 lemmas (end of PS1) and compute per verse rates by book.
2. Are the per-verse rates between Synoptic Gospels and John the same for all 5 lemmas.
3. Report effect sizes using Cohen's d along with confidence intervals.
4. Correct these results for multiple tests using the Bonferroni correction.
5. Correct these results for multiple tests using the Benjamini-Hochberg correction.
6. Why are the numbers from the Bonferroni correction different from the Benjamini-Hochberg correction? Which results should you use and why?

### Proportion
7. Are the proportion of term presence vs term absence in verse the same between Synoptic Gospels and John for all 5 lemmas?
8. Report effect sizes using Cohen's d along with confidence intervals.
9. Correct these results for multiple tests using the Bonferroni correction.
10. Correct these results for multiple tests using the Benjamini-Hochberg correction.
6. Why are the numbers from the Bonferroni correction different from the Benjamini-Hochberg correction? Which results should you use and why?

### ANOVA
12. Do a term rate ANOVA comparison on a theologically salient lemma from the top 20 lemmas across the following groups: {Matthew and Mark, Luke and Acts, Johannine books, Pauline books, all other books}
13. Perform a Post-hoc Tukey HSD to see which pairs differ

### Chi-square Test
14. Build a 2xk contingency table for collocation: presence of target term vs top-k companion terms within verse.
15. Run Chi-square tests of independence; compute standardized residuals to find surprising co-occurrences
16. Visualize a heatmap of residuals
17. Explain results

18. Repeat the ANOVA and Chi-square test sections for 2 other terms.

## Power Analysis Extension

18. Conduct a power analysis for the question in #7 to determine how many verses are needed to detect the specified effect.
13. Simulate the answer.
    <ol type="a">
    <li>Simulate n verses with the proportions found in #8 for Synoptic Gospels and John. Do a test to see if significantly different and save this result.</li>
    <li>Repeat step a many times.</li>
    <li>Calculate power: power = (number of significant findings) / (total simulations)</li>
    <li>Repeat steps a-c for a different n.</li>
    <li>Plot power as a function of number of verses.</li>
    <li>At what number of verses is the power at least 80%? i.e. This is the number of verses you need per text to have an 80% chance of detecting the effect if it's really there.</li>
    </ol>

## Sliding Windows Stretch
21. Repeat ANOVA and Chi-square sections on the same three theological terms, but instead of using verse boundaries, use sliding windows (+/- n tokens)
22. How do results of verse boundaries compare to using sliding windows?

## **Problem 1**: Identify 5 theologically salient lemmas from the top 20 lemmas (end of PS1) and compute per verse rates by book.

In [155]:
import pandas as pd

new_testament = pd.read_pickle('../Data/nt.pickle')
top20 = pd.read_pickle("../Data/zipf-top20.pickle")
strongs_dictionary = pd.read_pickle("./pickles/ps1/strongs_dictionary")

##### Finding "Salient" top 20 words (I.E Verbs/Nouns/Adjectives/Adverbs)

In [156]:
new_testament = pd.merge(
    strongs_dictionary,
    new_testament, 
    left_index=True, 
    right_on="strong"
)

In [157]:
# Forming Part of Speech
new_testament["part_speech"] = new_testament["parsed_rmac"].apply(lambda x: x.split()[0])
wanted_part_speech = ["Adjective", "Adverb","Noun","Verb"]
salient_nt = new_testament[new_testament['part_speech'].isin(wanted_part_speech)]

In [158]:
salient_nt['strong'].value_counts()

strong
1510    27049
3004    24761
2316    14432
3956    13475
2424     9944
        ...
3707       11
3703       11
3702       11
3700       11
3698       11
Name: count, Length: 5030, dtype: int64

In [174]:
top20_strongs_num = salient_nt['strong'].value_counts()[:20]
top20_df = pd.merge(
    left = top20_strongs_num,
    right = new_testament,
    left_index = True,
    right_on= "strong"
)
top20_df = top20_df.drop_duplicates(subset=['strong'], inplace=False)
top20_df

,count,greek-word,kjv-def,word,rmac,strong,book,chapter,verse,parsed_rmac,strong_definition,part_speech
282,27049,εἰμί,"am, have been, X it is I, was",ἦν.,V-IAI-3S,1510,40,1,18,Verb - Imperfect - Active - Indicative - 3rd -...,εἰμί the first person singular present indicat...,Verb
244,24761,λέγω,"ask, bid, boast, call, describe, give out, nam...",λεγόμενος,V-PPP-NSM,3004,40,1,16,Verb - Present - Passive - Participle - Nomina...,"λέγω a primary verb; properly, to ""lay"" forth,...",Verb
402,14432,θεός,"X exceeding, God, god(-ly, -ward)",θεός.,N-NSM,2316,40,1,23,Noun - Nominative - Singular - Masculine,"θεός of uncertain affinity; a deity, especiall...",Noun
246,13475,πᾶς,"all (manner of, means), alway(-s), any (one), ...",Πᾶσαι,A-NPF,3956,40,1,17,Adjective - Nominative - Plural - Feminine,πᾶς including all the forms of declension; app...,Adjective
2,9944,Ἰησοῦς,Jesus,Ἰησοῦ,N-GSM,2424,40,1,1,Noun - Genitive - Singular - Masculine,Ἰησοῦς of Hebrew origin (יְהוֹשׁ֫וּעַ); Jesus (i....,Noun
323,7876,κύριος,"God, Lord, master, Sir",κυρίου,N-GSM,2962,40,1,20,Noun - Genitive - Singular - Masculine,κύριος from kuros (supremacy); supreme in auth...,Noun
297,7755,ἔχω,"be (able, X hold, possessed with), accompany, ...",ἔχουσα,V-PAP-NSF,2192,40,1,18,Verb - Present - Active - Participle - Nominat...,ἔχω; including an alternate form scheo (used i...,Verb
321,7513,ὁράω,"behold, perceive, see, take heed",ἰδοὺ,V-2AAM-2S,3708,40,1,20,Verb - Second - Aorist - Active - Imperative -...,"ὁράω properly, to stare at (compare ὀπτάνομαι)...",Verb
370,7337,γίνομαι,"arise, be assembled, be(-come, -fall, -have se...",γέγονεν,V-2RAI-3S,1096,40,1,22,Verb - Second - Perfect - Active - Indicative ...,γίνομαι a prolongation and middle voice form o...,Verb
472,6886,ἔρχομαι,"accompany, appear, bring, come, enter, fall ou...",ἤλθομεν,V-2AAI-1P,2064,40,2,2,Verb - Second - Aorist - Active - Indicative -...,ἔρχομαι middle voice of a primary verb (used o...,Verb
409,6259,ποιέω,"abide, + agree, appoint, X avenge, + band toge...",ἐποίησεν,V-AAI-3S,4160,40,1,24,Verb - Aorist - Active - Indicative - 3rd - Si...,ποιέω apparently a prolonged form of an obsole...,Verb
1272,6050,ἄνθρωπος,"certain, man","ἄνθρωπος,",N-NSM,444,40,4,4,Noun - Nominative - Singular - Masculine,ἄνθρωπος from ἀνήρ and ops (the countenance; f...,Noun
3,5830,Χριστός,Christ,Χριστοῦ,N-GSM,5547,40,1,1,Noun - Genitive - Singular - Masculine,"Χριστός from χρίω; anointed, i.e. the Messiah,...",Noun
410,5511,ὡς,"about, after (that), (according) as (it had be...",ὡς,ADV,5613,40,1,24,Adverb or adverb and particle combined,ὡς probably adverb of comparative from ὅς; whi...,Adverb
475,4686,ἀκούω,"give (in the) audience (of), come (to the ears...",ἀκούσας,V-AAP-NSM,191,40,2,3,Verb - Aorist - Active - Participle - Nominati...,ἀκούω a primary verb; to hear (in various sens...,Verb
1369,4554,δίδωμι,"adventure, bestow, bring forth, commit, delive...",δώσω,V-FAI-1S,1325,40,4,9,Verb - Future - Active - Indicative - 1st - Si...,δίδωμι a prolonged form of a primary verb (whi...,Verb
859,4532,πατήρ,"father, parent",πατρὸς,N-GSM,3962,40,2,22,Noun - Genitive - Singular - Masculine,"πατήρ apparently a primary word; a ""father"" (l...",Noun
444,4268,ἡμέρα,"age, + alway, (mid-)day (by day, (-ly)), + for...",ἡμέραις,N-DPF,2250,40,2,1,Noun - Dative - Plural - Feminine,ἡμέρα feminine (with ὥρα implied) of a derivat...,Noun
299,4169,πνεῦμα,"ghost, life, spirit(-ual, -ually), mind",πνεύματος,N-GSN,4151,40,1,18,Noun - Genitive - Singular - Neuter,"πνεῦμα from πνέω; a current of air, i.e. breat...",Noun
4,4136,υἱός,"child, foal, son",υἱοῦ,N-GSM,5207,40,1,1,Noun - Genitive - Singular - Masculine,"υἱός apparently a primary word; a ""son"" (somet...",Noun

##### Finding the "per verse" rates by book.

In [162]:
# salient_words = ["κύριος", "υἱός", "Ἰησοῦς", "εἰμί", "πατήρ"]
# salient_nt = new_testament[new_testament['word'].isin(salient_words)]
# print(salient_nt['word'].value_counts())
# # def per_verse(group):


# # Collect occurences of words per book
# words_in_each_gospel = salient_nt.pivot_table(
#     index= "book",
#     columns = "word",
#     aggfunc = "size",
# )

# # Collect total number of verses per book
# verses_per_chapter = salient_nt.groupby(['book','chapter'])['verse'].max()
# verses_per_book = verses_per_chapter.groupby('book').sum()  


# per_verse_df = pd.merge(verses_per_book, words_in_each_gospel, on="book")
# per_verse_df.fillna(0, inplace=True)
# per_verse_df = per_verse_df[["κύριος","πατήρ", "υἱός", "Ἰησοῦς"]].div(per_verse_df['verse'], axis=0)
# print(per_verse_df)

## Problem 2

In [163]:
synoptics = new_testament.query("book in [40,41,42]")
john = new_testament[new_testament["book"] == 43]

display(synoptics.head())
display(john.head())

,greek-word,kjv-def,word,rmac,strong,book,chapter,verse,parsed_rmac,strong_definition,part_speech
29557,Ἀαρών,Aaron,"Ἀαρών,",N-PRI,2,42,1,5,Indeclinable proper noun,"Ἀαρών of Hebrew origin (אַהֲרוֹן); Aaron, the br...",Indeclinable
27923,Ἀββᾶ,Abba,ἀββᾶ,N-PRI,5,41,14,36,Indeclinable proper noun,Ἀββᾶ of Chaldee origin (אַב); father as a vocat...,Indeclinable
14038,Ἄβελ,Abel,Ἅβελ,N-PRI,6,40,23,35,Indeclinable proper noun,"Ἄβελ of Hebrew origin (הָ֫בֶל); Abel, the son ...",Indeclinable
39419,Ἄβελ,Abel,Ἄβελ,N-PRI,6,42,11,51,Indeclinable proper noun,"Ἄβελ of Hebrew origin (הָ֫בֶל); Abel, the son ...",Indeclinable
108,Ἀβιά,Abia,"Ἀβιά,",N-PRI,7,40,1,7,Indeclinable proper noun,"Ἀβιά of Hebrew origin (אֲבִיָּה); Abijah, the n...",Indeclinable

,greek-word,kjv-def,word,rmac,strong,book,chapter,verse,parsed_rmac,strong_definition,part_speech
55199,Ἀβραάμ,Abraham,Ἀβραάμ,N-PRI,11,43,8,33,Indeclinable proper noun,"Ἀβραάμ of Hebrew origin (אַבְרָהָם); Abraham, t...",Indeclinable
55258,Ἀβραάμ,Abraham,Ἀβραάμ,N-PRI,11,43,8,37,Indeclinable proper noun,"Ἀβραάμ of Hebrew origin (אַבְרָהָם); Abraham, t...",Indeclinable
55296,Ἀβραάμ,Abraham,Ἀβραάμ,N-PRI,11,43,8,39,Indeclinable proper noun,"Ἀβραάμ of Hebrew origin (אַבְרָהָם); Abraham, t...",Indeclinable
55305,Ἀβραάμ,Abraham,Ἀβραάμ,N-PRI,11,43,8,39,Indeclinable proper noun,"Ἀβραάμ of Hebrew origin (אַבְרָהָם); Abraham, t...",Indeclinable
55310,Ἀβραάμ,Abraham,Ἀβραὰμ,N-PRI,11,43,8,39,Indeclinable proper noun,"Ἀβραάμ of Hebrew origin (אַבְרָהָם); Abraham, t...",Indeclinable